services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend